/**
 * idm.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import IdmDownloadType from './IdmDownloadType';

/**
 * The IdmCreateDownloadTaskRequest model module.
 * @module model/IdmCreateDownloadTaskRequest
 * @version version not set
 */
class IdmCreateDownloadTaskRequest {
    /**
     * Constructs a new <code>IdmCreateDownloadTaskRequest</code>.
     * @alias module:model/IdmCreateDownloadTaskRequest
     */
    constructor() { 
        
        IdmCreateDownloadTaskRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>IdmCreateDownloadTaskRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/IdmCreateDownloadTaskRequest} obj Optional instance to populate.
     * @return {module:model/IdmCreateDownloadTaskRequest} The populated <code>IdmCreateDownloadTaskRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new IdmCreateDownloadTaskRequest();

            if (data.hasOwnProperty('downloadType')) {
                obj['downloadType'] = IdmDownloadType.constructFromObject(data['downloadType']);
            }
            if (data.hasOwnProperty('url')) {
                obj['url'] = ApiClient.convertToType(data['url'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>IdmCreateDownloadTaskRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>IdmCreateDownloadTaskRequest</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['url'] && !(typeof data['url'] === 'string' || data['url'] instanceof String)) {
            throw new Error("Expected the field `url` to be a primitive type in the JSON string but got " + data['url']);
        }

        return true;
    }


}



/**
 * @member {module:model/IdmDownloadType} downloadType
 */
IdmCreateDownloadTaskRequest.prototype['downloadType'] = undefined;

/**
 * @member {String} url
 */
IdmCreateDownloadTaskRequest.prototype['url'] = undefined;






export default IdmCreateDownloadTaskRequest;

