/**
 * idm.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import IdmAccount from './IdmAccount';
import IdmDownloadStatus from './IdmDownloadStatus';
import IdmDownloadType from './IdmDownloadType';

/**
 * The IdmDownloadTask model module.
 * @module model/IdmDownloadTask
 * @version version not set
 */
class IdmDownloadTask {
    /**
     * Constructs a new <code>IdmDownloadTask</code>.
     * @alias module:model/IdmDownloadTask
     */
    constructor() { 
        
        IdmDownloadTask.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>IdmDownloadTask</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/IdmDownloadTask} obj Optional instance to populate.
     * @return {module:model/IdmDownloadTask} The populated <code>IdmDownloadTask</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new IdmDownloadTask();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('ofAccount')) {
                obj['ofAccount'] = IdmAccount.constructFromObject(data['ofAccount']);
            }
            if (data.hasOwnProperty('downloadType')) {
                obj['downloadType'] = IdmDownloadType.constructFromObject(data['downloadType']);
            }
            if (data.hasOwnProperty('url')) {
                obj['url'] = ApiClient.convertToType(data['url'], 'String');
            }
            if (data.hasOwnProperty('downloadStatus')) {
                obj['downloadStatus'] = IdmDownloadStatus.constructFromObject(data['downloadStatus']);
            }
            if (data.hasOwnProperty('metadata')) {
                obj['metadata'] = ApiClient.convertToType(data['metadata'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>IdmDownloadTask</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>IdmDownloadTask</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // validate the optional field `ofAccount`
        if (data['ofAccount']) { // data not null
          IdmAccount.validateJSON(data['ofAccount']);
        }
        // ensure the json data is a string
        if (data['url'] && !(typeof data['url'] === 'string' || data['url'] instanceof String)) {
            throw new Error("Expected the field `url` to be a primitive type in the JSON string but got " + data['url']);
        }
        // ensure the json data is a string
        if (data['metadata'] && !(typeof data['metadata'] === 'string' || data['metadata'] instanceof String)) {
            throw new Error("Expected the field `metadata` to be a primitive type in the JSON string but got " + data['metadata']);
        }

        return true;
    }


}



/**
 * @member {String} id
 */
IdmDownloadTask.prototype['id'] = undefined;

/**
 * @member {module:model/IdmAccount} ofAccount
 */
IdmDownloadTask.prototype['ofAccount'] = undefined;

/**
 * @member {module:model/IdmDownloadType} downloadType
 */
IdmDownloadTask.prototype['downloadType'] = undefined;

/**
 * @member {String} url
 */
IdmDownloadTask.prototype['url'] = undefined;

/**
 * @member {module:model/IdmDownloadStatus} downloadStatus
 */
IdmDownloadTask.prototype['downloadStatus'] = undefined;

/**
 * @member {String} metadata
 */
IdmDownloadTask.prototype['metadata'] = undefined;






export default IdmDownloadTask;

