/**
 * idm.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The IdmGetDownloadTaskFileResponse model module.
 * @module model/IdmGetDownloadTaskFileResponse
 * @version version not set
 */
class IdmGetDownloadTaskFileResponse {
    /**
     * Constructs a new <code>IdmGetDownloadTaskFileResponse</code>.
     * @alias module:model/IdmGetDownloadTaskFileResponse
     */
    constructor() { 
        
        IdmGetDownloadTaskFileResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>IdmGetDownloadTaskFileResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/IdmGetDownloadTaskFileResponse} obj Optional instance to populate.
     * @return {module:model/IdmGetDownloadTaskFileResponse} The populated <code>IdmGetDownloadTaskFileResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new IdmGetDownloadTaskFileResponse();

            if (data.hasOwnProperty('data')) {
                obj['data'] = ApiClient.convertToType(data['data'], 'Blob');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>IdmGetDownloadTaskFileResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>IdmGetDownloadTaskFileResponse</code>.
     */
    static validateJSON(data) {

        return true;
    }


}



/**
 * @member {Blob} data
 */
IdmGetDownloadTaskFileResponse.prototype['data'] = undefined;






export default IdmGetDownloadTaskFileResponse;

