/**
 * idm.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import IdmDownloadTask from './IdmDownloadTask';

/**
 * The IdmUpdateDownloadTaskResponse model module.
 * @module model/IdmUpdateDownloadTaskResponse
 * @version version not set
 */
class IdmUpdateDownloadTaskResponse {
    /**
     * Constructs a new <code>IdmUpdateDownloadTaskResponse</code>.
     * @alias module:model/IdmUpdateDownloadTaskResponse
     */
    constructor() { 
        
        IdmUpdateDownloadTaskResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>IdmUpdateDownloadTaskResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/IdmUpdateDownloadTaskResponse} obj Optional instance to populate.
     * @return {module:model/IdmUpdateDownloadTaskResponse} The populated <code>IdmUpdateDownloadTaskResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new IdmUpdateDownloadTaskResponse();

            if (data.hasOwnProperty('downloadTask')) {
                obj['downloadTask'] = IdmDownloadTask.constructFromObject(data['downloadTask']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>IdmUpdateDownloadTaskResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>IdmUpdateDownloadTaskResponse</code>.
     */
    static validateJSON(data) {
        // validate the optional field `downloadTask`
        if (data['downloadTask']) { // data not null
          IdmDownloadTask.validateJSON(data['downloadTask']);
        }

        return true;
    }


}



/**
 * @member {module:model/IdmDownloadTask} downloadTask
 */
IdmUpdateDownloadTaskResponse.prototype['downloadTask'] = undefined;






export default IdmUpdateDownloadTaskResponse;

