/**
 * idm.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import IdmGetDownloadTaskFileResponse from './IdmGetDownloadTaskFileResponse';
import RpcStatus from './RpcStatus';

/**
 * The StreamResultOfIdmGetDownloadTaskFileResponse model module.
 * @module model/StreamResultOfIdmGetDownloadTaskFileResponse
 * @version version not set
 */
class StreamResultOfIdmGetDownloadTaskFileResponse {
    /**
     * Constructs a new <code>StreamResultOfIdmGetDownloadTaskFileResponse</code>.
     * @alias module:model/StreamResultOfIdmGetDownloadTaskFileResponse
     */
    constructor() { 
        
        StreamResultOfIdmGetDownloadTaskFileResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>StreamResultOfIdmGetDownloadTaskFileResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/StreamResultOfIdmGetDownloadTaskFileResponse} obj Optional instance to populate.
     * @return {module:model/StreamResultOfIdmGetDownloadTaskFileResponse} The populated <code>StreamResultOfIdmGetDownloadTaskFileResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new StreamResultOfIdmGetDownloadTaskFileResponse();

            if (data.hasOwnProperty('result')) {
                obj['result'] = IdmGetDownloadTaskFileResponse.constructFromObject(data['result']);
            }
            if (data.hasOwnProperty('error')) {
                obj['error'] = RpcStatus.constructFromObject(data['error']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>StreamResultOfIdmGetDownloadTaskFileResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>StreamResultOfIdmGetDownloadTaskFileResponse</code>.
     */
    static validateJSON(data) {
        // validate the optional field `result`
        if (data['result']) { // data not null
          IdmGetDownloadTaskFileResponse.validateJSON(data['result']);
        }
        // validate the optional field `error`
        if (data['error']) { // data not null
          RpcStatus.validateJSON(data['error']);
        }

        return true;
    }


}



/**
 * @member {module:model/IdmGetDownloadTaskFileResponse} result
 */
StreamResultOfIdmGetDownloadTaskFileResponse.prototype['result'] = undefined;

/**
 * @member {module:model/RpcStatus} error
 */
StreamResultOfIdmGetDownloadTaskFileResponse.prototype['error'] = undefined;






export default StreamResultOfIdmGetDownloadTaskFileResponse;

