/**
 * idm.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.IdmProto);
  }
}(this, function(expect, IdmProto) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new IdmProto.IdmServiceApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('IdmServiceApi', function() {
    describe('idmServiceCreateAccount', function() {
      it('should call idmServiceCreateAccount successfully', function(done) {
        //uncomment below and update the code to test idmServiceCreateAccount
        //instance.idmServiceCreateAccount(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('idmServiceCreateDownloadTask', function() {
      it('should call idmServiceCreateDownloadTask successfully', function(done) {
        //uncomment below and update the code to test idmServiceCreateDownloadTask
        //instance.idmServiceCreateDownloadTask(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('idmServiceCreateSession', function() {
      it('should call idmServiceCreateSession successfully', function(done) {
        //uncomment below and update the code to test idmServiceCreateSession
        //instance.idmServiceCreateSession(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('idmServiceDeleteDownloadTask', function() {
      it('should call idmServiceDeleteDownloadTask successfully', function(done) {
        //uncomment below and update the code to test idmServiceDeleteDownloadTask
        //instance.idmServiceDeleteDownloadTask(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('idmServiceDeleteSession', function() {
      it('should call idmServiceDeleteSession successfully', function(done) {
        //uncomment below and update the code to test idmServiceDeleteSession
        //instance.idmServiceDeleteSession(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('idmServiceGetDownloadTaskFile', function() {
      it('should call idmServiceGetDownloadTaskFile successfully', function(done) {
        //uncomment below and update the code to test idmServiceGetDownloadTaskFile
        //instance.idmServiceGetDownloadTaskFile(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('idmServiceGetDownloadTaskList', function() {
      it('should call idmServiceGetDownloadTaskList successfully', function(done) {
        //uncomment below and update the code to test idmServiceGetDownloadTaskList
        //instance.idmServiceGetDownloadTaskList(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('idmServiceUpdateDownloadTask', function() {
      it('should call idmServiceUpdateDownloadTask successfully', function(done) {
        //uncomment below and update the code to test idmServiceUpdateDownloadTask
        //instance.idmServiceUpdateDownloadTask(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
