/**
 * idm.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import IdmAccount from './model/IdmAccount';
import IdmCreateAccountRequest from './model/IdmCreateAccountRequest';
import IdmCreateAccountResponse from './model/IdmCreateAccountResponse';
import IdmCreateDownloadTaskRequest from './model/IdmCreateDownloadTaskRequest';
import IdmCreateDownloadTaskResponse from './model/IdmCreateDownloadTaskResponse';
import IdmCreateSessionRequest from './model/IdmCreateSessionRequest';
import IdmCreateSessionResponse from './model/IdmCreateSessionResponse';
import IdmDownloadStatus from './model/IdmDownloadStatus';
import IdmDownloadTask from './model/IdmDownloadTask';
import IdmDownloadType from './model/IdmDownloadType';
import IdmGetDownloadTaskFileResponse from './model/IdmGetDownloadTaskFileResponse';
import IdmGetDownloadTaskListResponse from './model/IdmGetDownloadTaskListResponse';
import IdmServiceUpdateDownloadTaskBody from './model/IdmServiceUpdateDownloadTaskBody';
import IdmUpdateDownloadTaskResponse from './model/IdmUpdateDownloadTaskResponse';
import ProtobufAny from './model/ProtobufAny';
import RpcStatus from './model/RpcStatus';
import StreamResultOfIdmGetDownloadTaskFileResponse from './model/StreamResultOfIdmGetDownloadTaskFileResponse';
import IdmServiceApi from './api/IdmServiceApi';


/**
* JS API client generated by OpenAPI Generator.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var IdmProto = require('index'); // See note below*.
* var xxxSvc = new IdmProto.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new IdmProto.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new IdmProto.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new IdmProto.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version version not set
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The IdmAccount model constructor.
     * @property {module:model/IdmAccount}
     */
    IdmAccount,

    /**
     * The IdmCreateAccountRequest model constructor.
     * @property {module:model/IdmCreateAccountRequest}
     */
    IdmCreateAccountRequest,

    /**
     * The IdmCreateAccountResponse model constructor.
     * @property {module:model/IdmCreateAccountResponse}
     */
    IdmCreateAccountResponse,

    /**
     * The IdmCreateDownloadTaskRequest model constructor.
     * @property {module:model/IdmCreateDownloadTaskRequest}
     */
    IdmCreateDownloadTaskRequest,

    /**
     * The IdmCreateDownloadTaskResponse model constructor.
     * @property {module:model/IdmCreateDownloadTaskResponse}
     */
    IdmCreateDownloadTaskResponse,

    /**
     * The IdmCreateSessionRequest model constructor.
     * @property {module:model/IdmCreateSessionRequest}
     */
    IdmCreateSessionRequest,

    /**
     * The IdmCreateSessionResponse model constructor.
     * @property {module:model/IdmCreateSessionResponse}
     */
    IdmCreateSessionResponse,

    /**
     * The IdmDownloadStatus model constructor.
     * @property {module:model/IdmDownloadStatus}
     */
    IdmDownloadStatus,

    /**
     * The IdmDownloadTask model constructor.
     * @property {module:model/IdmDownloadTask}
     */
    IdmDownloadTask,

    /**
     * The IdmDownloadType model constructor.
     * @property {module:model/IdmDownloadType}
     */
    IdmDownloadType,

    /**
     * The IdmGetDownloadTaskFileResponse model constructor.
     * @property {module:model/IdmGetDownloadTaskFileResponse}
     */
    IdmGetDownloadTaskFileResponse,

    /**
     * The IdmGetDownloadTaskListResponse model constructor.
     * @property {module:model/IdmGetDownloadTaskListResponse}
     */
    IdmGetDownloadTaskListResponse,

    /**
     * The IdmServiceUpdateDownloadTaskBody model constructor.
     * @property {module:model/IdmServiceUpdateDownloadTaskBody}
     */
    IdmServiceUpdateDownloadTaskBody,

    /**
     * The IdmUpdateDownloadTaskResponse model constructor.
     * @property {module:model/IdmUpdateDownloadTaskResponse}
     */
    IdmUpdateDownloadTaskResponse,

    /**
     * The ProtobufAny model constructor.
     * @property {module:model/ProtobufAny}
     */
    ProtobufAny,

    /**
     * The RpcStatus model constructor.
     * @property {module:model/RpcStatus}
     */
    RpcStatus,

    /**
     * The StreamResultOfIdmGetDownloadTaskFileResponse model constructor.
     * @property {module:model/StreamResultOfIdmGetDownloadTaskFileResponse}
     */
    StreamResultOfIdmGetDownloadTaskFileResponse,

    /**
    * The IdmServiceApi service constructor.
    * @property {module:api/IdmServiceApi}
    */
    IdmServiceApi
};
