// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wiring

import (
	"github.com/google/wire"
	"github.com/maxuanquang/idm/internal/configs"
	"github.com/maxuanquang/idm/internal/dataaccess"
	"github.com/maxuanquang/idm/internal/dataaccess/database"
	"github.com/maxuanquang/idm/internal/handler"
	"github.com/maxuanquang/idm/internal/handler/grpc"
	"github.com/maxuanquang/idm/internal/handler/http"
	"github.com/maxuanquang/idm/internal/logic"
	"github.com/maxuanquang/idm/internal/utils"
)

// Injectors from wire.go:

func InitializeGRPCServer(configFilePath configs.ConfigFilePath) (grpc.Server, func(), error) {
	config, err := configs.NewConfig(configFilePath)
	if err != nil {
		return nil, nil, err
	}
	configsDatabase := config.Database
	databaseDatabase, cleanup, err := database.InitializeDB(configsDatabase)
	if err != nil {
		return nil, nil, err
	}
	accountDataAccessor := database.NewAccountDataAccessor(databaseDatabase)
	accountPasswordDataAccessor := database.NewAccountPasswordDataAccessor(databaseDatabase)
	hash := logic.NewHash()
	log := config.Log
	logger, cleanup2, err := utils.InitializeLogger(log)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	tokenPublicKeyDataAccessor, err := database.NewTokenPublicKeyDataAccessor(databaseDatabase, logger)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	auth := config.Auth
	token, err := logic.NewToken(accountDataAccessor, tokenPublicKeyDataAccessor, logger, auth)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	account := logic.NewAccount(databaseDatabase, accountDataAccessor, accountPasswordDataAccessor, hash, token)
	idmServiceServer := grpc.NewHandler(account)
	server := grpc.NewServer(idmServiceServer)
	return server, func() {
		cleanup2()
		cleanup()
	}, nil
}

func InitializeHTTPServer(configFilePath configs.ConfigFilePath) (http.Server, func(), error) {
	server := http.NewServer()
	return server, func() {
	}, nil
}

// wire.go:

var WireSet = wire.NewSet(configs.WireSet, dataaccess.WireSet, handler.WireSet, logic.WireSet, utils.WireSet)
